// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	context "context"
	models "mock_example/models"

	mock "github.com/stretchr/testify/mock"
)

// EventNotifier is an autogenerated mock type for the EventNotifier type
type EventNotifier struct {
	mock.Mock
}

// NotifyUserCreated provides a mock function with given fields: ctx, user
func (_m *EventNotifier) NotifyUserCreated(ctx context.Context, user models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for NotifyUserCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventNotifier creates a new instance of EventNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventNotifier(t interface {
	mock.TestingT
	Cleanup(func())
},
) *EventNotifier {
	mock := &EventNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
